# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'vFlair' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vFlair

  target 'vFlairTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'vFlairUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Fabric'
pod 'Crashlytics'
pod 'Firebase/Performance'
pod 'Firebase/DynamicLinks'
pod 'SDWebImage'
pod 'RAMAnimatedTabBarController'
pod 'expanding-collection'
pod 'RAMPaperSwitch'


end
